name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish ${{ matrix.template }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        template: [undergraduate-thesis, undergraduate-proposal-report, lab-report, paper-translation, presentation-slide, master-thesis]

    steps:
      - uses: actions/checkout@v2
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip files under ./${{ matrix.template }}
        run: zip -qq -r ./${{ matrix.template }}.zip ./${{ matrix.template }}
        working-directory: ./templates
      - name: Upload ${{ matrix.template }}.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./templates/${{ matrix.template }}.zip
          asset_name: ${{ matrix.template }}.zip
          tag: ${{ github.ref }}
