on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
            make test
